// File generated by FlutterFire CLI. Run: flutterfire configure
//
// Configured for project: admission-management-sys-a89a3
// Android, Web, Windows have real credentials. iOS/macOS use placeholders (add iOS app in Firebase if needed).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCceMZ2lQO0HE4Q7Ei_15CiCh6FkIzn-fE',
    appId: '1:205951110639:android:2fe6652ad6a24a33f93a1a',
    messagingSenderId: '205951110639',
    projectId: 'admission-management-sys-a89a3',
    storageBucket: 'admission-management-sys-a89a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnlyReplaceWithReal',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'admission-management-demo',
    storageBucket: 'admission-management-demo.appspot.com',
    iosBundleId: 'com.admission.admissionManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopmentOnlyReplaceWithReal',
    appId: '1:000000000000:ios:0000000000000000000001',
    messagingSenderId: '000000000000',
    projectId: 'admission-management-demo',
    storageBucket: 'admission-management-demo.appspot.com',
    iosBundleId: 'com.admission.admissionManagement',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03n_XoD-nn2XxGP0HA-WWPkQkB6j9Kwg',
    appId: '1:205951110639:web:15f99513761888cbf93a1a',
    messagingSenderId: '205951110639',
    projectId: 'admission-management-sys-a89a3',
    authDomain: 'admission-management-sys-a89a3.firebaseapp.com',
    storageBucket: 'admission-management-sys-a89a3.firebasestorage.app',
    measurementId: 'G-J8454K0NKC',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD03n_XoD-nn2XxGP0HA-WWPkQkB6j9Kwg',
    appId: '1:205951110639:web:3531f74e302ce263f93a1a',
    messagingSenderId: '205951110639',
    projectId: 'admission-management-sys-a89a3',
    authDomain: 'admission-management-sys-a89a3.firebaseapp.com',
    storageBucket: 'admission-management-sys-a89a3.firebasestorage.app',
    measurementId: 'G-1789RR4RGN',
  );

}